[main]
font=Inter:size=12
prompt="> "
lines=10
width=50
tabs=4
horizontal-pad=40
vertical-pad=20
inner-pad=10

# On retire le mode dmenu pour qu'il liste tes applications par défaut
dmenu=no

[colors]
background=00000099       # Violet très foncé
text=f8f8f2ff             # Blanc-gris clair
input=f8f8f2ff            # Texte recherché
match=94e2d5ff            # Lettres correspondantes (Turquoise doux)
selection=d3b6f2ff        # Barre de sélection en violet (opaque)
selection-text=282a36ff   # Texte à l'intérieur en sombre pour rester bien lisible
selection-match=94e2d5ff  # Lettres correspondantes sélectionnées
border=cba6f7ff           # Bordure (Violet pastel éclatant)

[border]
width=2
radius=0
