# --- APPARENCE GÉNÉRALE ---

background_opacity 0.80

#hide_window_decorations yes

window_padding_width 15

background #1a1a1a

# --- TAILLE DE LA FENÊTRE ---

# (Ajout pour agrandir la fenêtre au démarrage)

remember_window_size  no

initial_window_width  100c

initial_window_height 22c

# --- POLICE ---

font_family      JetBrains Mono

bold_font        auto

italic_font      auto

bold_italic_font auto

font_size 11.0

# Optimisation du rendu

box_drawing_scale 0.001, 1, 1.5, 2

# --- COULEURS ET ACCENTS (Pocillo-frappe / Catppuccin Frappé) ---

background            #303446
foreground            #c6d0f5

cursor                #CA9EE6
cursor_text_color     #303446

selection_foreground  #303446
selection_background  #ca9ee6

active_border_color   #8caaee
inactive_border_color #414559

# Couleurs ANSI
color0   #51576d
color1   #e78284
color2   #a6d189
color3   #e5c890
color4   #8caaee
color5   #ca9ee6
color6   #81c8be
color7   #b5bfe2
color8   #626880
color9   #e78284
color10  #a6d189
color11  #e5c890
color12  #8caaee
color13  #ca9ee6
color14  #81c8be
color15  #a5adce

# --- PERFORMANCE ---

repaint_delay 10

input_delay 3

sync_to_monitor yes


